PACKAGE_NAME="iwlwifi-lar-disable"
PACKAGE_VERSION="1.0"
PRE_BUILD="pre_build_ubuntu.sh"
CLEAN="make -C /lib/modules/${kernelver}/build M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build/drivers/net/wireless/intel/iwlwifi clean"
MAKE[0]="make -C /lib/modules/${kernelver}/build M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build/drivers/net/wireless/intel/iwlwifi modules"
BUILT_MODULE_NAME[0]="iwlmvm"
BUILT_MODULE_LOCATION[0]="drivers/net/wireless/intel/iwlwifi/mvm"
DEST_MODULE_LOCATION[0]="/updates"
AUTOINSTALL="yes"
BUILD_EXCLUSIVE_KERNEL_MIN="6.11"
