name: Build and Push to Vorvan

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - id: 'auth'
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_CRED_JSON }}'
      - name: Configure Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet #authenticate to gcr
      - name: Docker Build Image
        run: |-
          docker build -t gcr.io/$GCLOUD_PROJECT/h2oai/h2o-llmstudio:nightly .
      - name: Push to Vorvan
        run: |-
          docker push gcr.io/$GCLOUD_PROJECT/h2oai/h2o-llmstudio:nightly
